package pojogue;
// Generated Oct 17, 2022 3:06:59 AM by Hibernate Tools 4.3.1

import MODELUK.DAOEdmin;
import MODELUK.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean


/**
 * TblEdmin generated by hbm2java
 */
public class TblEdmin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public TblEdmin() {
    }

    public TblEdmin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String validasiLogin(){
        DAOLogin uDao = new DAOLogin();
        List<TblEdmin> us = uDao.getBy(username, password);
        try{
        if (!us.isEmpty()) {
                username = us.get(0).username;
                password = us.get(0).password;
                return "edmin";
            } else{
                
            }
        } catch (Exception e) {
            System.out.println(e);
            username = "";
            password = "";
        }
        return "index";
    }
    public String logout() {   
	return "index";
    }
    
    public List<TblEdmin> getallrecords(){
        DAOEdmin plg = new DAOEdmin();
        List<TblEdmin> lplg = plg.retrieveTblAdmin();
        return lplg;
    }
    
    public List<TblEdmin> getbyid(){
        DAOEdmin adao = new DAOEdmin();
        List<TblEdmin> ldao = adao.getbyID1(id);
        username = ldao.get(0).username;
        password = ldao.get(0).password;
        
        return ldao;
    }
    
    public void update(){
        DAOEdmin uadao = new DAOEdmin();
        uadao.edminUpdate(this);
        
        username = "";
    }



}


