package pojogue;
// Generated Oct 17, 2022 3:06:59 AM by Hibernate Tools 4.3.1

import MODELUK.DAOProduk;
import java.util.List;
import javax.faces.bean.ManagedBean;


@ManagedBean
(name = "fd")
/**
 * TblProduk generated by hbm2java
 */

public class TblProduk  implements java.io.Serializable {


     private Integer produkId;
     private String produkName;
     private int stok;
     private int harga;
     private String ukuran;
     
        public List<TblProduk> getallrecords(){
        DAOProduk plg = new DAOProduk();
        List<TblProduk> lplg = plg.retrieveTblProduk();
        return lplg;
        }
     
        public String getById() {
        String ids = Integer.toString(produkId);
        DAOProduk med = new DAOProduk();
        List<TblProduk> listMed = med.getbyID(produkId);
        try {

            if (!listMed.isEmpty()) {
                produkId = listMed.get(0).produkId;
                produkName = listMed.get(0).produkName;
                stok = listMed.get(0).stok;
                harga = listMed.get(0).harga;
                ukuran = listMed.get(0).ukuran;
                
                return "ep";
            } else {
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "produk";
    }
    
        public String deleteProd() {
        DAOProduk med = new DAOProduk();
        med.deleteMed(produkId);
     produkId = null;
     produkName = "";
     stok = 0;
     harga = 0;
     ukuran = "";
        return "produk";
    }
    public String editMed() {
      DAOProduk med = new DAOProduk();
      med.editMed(this);
     produkId = null;
     produkName = "";
     stok = 0;
     harga = 0;
     ukuran = "";     
     return "produk";
    }
    
     public String saveMed() {

     DAOProduk med = new DAOProduk();
     med.addMed(this);
     produkId = null;
     produkName = "";
     stok = 0;
     harga = 0;
     ukuran = "";
            
        return "produk";  
    }
    public String goBack(){

     produkId = null;
     produkName = "";
     stok = 0;
     harga = 0;
     ukuran = "";  
       return "produk";
    }
    public TblProduk() {
    }

    public TblProduk(String produkName, int stok, int harga, String ukuran) {
       this.produkName = produkName;
       this.stok = stok;
       this.harga = harga;
       this.ukuran = ukuran;
    }
   
    public Integer getProdukId() {
        return this.produkId;
    }
    
    public void setProdukId(Integer produkId) {
        this.produkId = produkId;
    }
    public String getProdukName() {
        return this.produkName;
    }
    
    public void setProdukName(String produkName) {
        this.produkName = produkName;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }
    public String getUkuran() {
        return this.ukuran;
    }
    
    public void setUkuran(String ukuran) {
        this.ukuran = ukuran;
    }


}


