package pojogue;
// Generated Oct 17, 2022 3:06:59 AM by Hibernate Tools 4.3.1



import MODELUK.DAOVendor;
import java.util.List;
import javax.faces.bean.ManagedBean;

@ManagedBean


/**
 * TblVendor generated by hbm2java
 */
public class TblVendor  implements java.io.Serializable {


     private Integer vendorId;
     private String vendorName;
     private String vendorAddress;

    public TblVendor() {
    }

    public TblVendor(String vendorName, String vendorAddress) {
       this.vendorName = vendorName;
       this.vendorAddress = vendorAddress;
    }
   
    public Integer getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }
    public String getVendorAddress() {
        return this.vendorAddress;
    }
    
    public void setVendorAddress(String vendorAddress) {
        this.vendorAddress = vendorAddress;
    }
    
    public List<TblVendor> getallrecords(){
        DAOVendor plg = new DAOVendor();
        List<TblVendor> lplg = plg.retrieveVendor();
        return lplg;
    }
    
    
        public String getById() {
        String ids = Integer.toString(vendorId);
        DAOVendor med = new DAOVendor();
        List<TblVendor> listMed = med.getbyID(vendorId);
        try {

            if (!listMed.isEmpty()) {
                vendorId = listMed.get(0).vendorId;
                vendorName = listMed.get(0).vendorName;
                vendorAddress = listMed.get(0).vendorAddress;
                return "ev";
            } else {
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "vendor";
    }
    
        public String deleteVen() {
        DAOVendor med = new DAOVendor();
        med.deleteMed(vendorId);
     vendorId = null;
     vendorName = "";
     vendorAddress = "";
        return "vendor";
    }
    public String editMed() {
      DAOVendor med = new DAOVendor();
      med.editMed(this);
     vendorId = null;
     vendorName = "";
     vendorAddress = "";      
     return "vendor";
    }
    
        public String saveMed() {

            DAOVendor med = new DAOVendor();
            med.addMed(this);
            vendorId = null;
            vendorName = "";
            vendorAddress = "";   
            
        return "vendor";  
    }
    public String goBack(){

     vendorId = null;
     vendorName = "";
     vendorAddress = "";  
       return "vendor";
    }
    
    
   



}


